name: Build Zed Stable

on:
  schedule:
    - cron: "0 0 * * *" # Runs every night at midnight UTC
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Changed to Windows runner

    steps:
      - name: Enable long paths in git
        run: git config --system core.longpaths true
        shell: pwsh

      - name: Enable long paths in Windows
        run: |
          New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
            -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
        shell: pwsh

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: zed-industries/zed
          ref: main

      - name: Install rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: x86_64-pc-windows-msvc

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.3

      - name: Build Zed
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://gist.githubusercontent.com/ashwinjadhav818/9733576b5e1996c3049c6a5512c15307/raw/ebbd7e028be6f50a79376ebc9d862e824233d1bd/zed-editor-windows-build.ps1" -OutFile "build-zed.ps1"
          .\build-zed.ps1

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: zed-windows
          path: |
            zed-install/*
            !zed-install/*.pdb

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v4
        with:
          name: zed-windows
          path: zed-windows

      - name: Get the current date
        id: date
        run: echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Create release archive
        run: |
          cd zed-windows
          zip -r ../zed-windows.zip ./*

      - name: Upload release build artifact to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.CURRENT_DATE }}
          tag_name: ${{ env.CURRENT_DATE }}
          draft: false
          make_latest: true
          files: zed-windows.zip
